replicaCount: 1
pageMessage: "Development environment"
ingress:
  enabled: true
  className: nginx
  host: dev.localdev.me
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 64Mi
