persistence:
  enabled: false

adminPassword: admin

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        url: http://prom-prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: lab
        orgId: 1
        folder: Lab
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/lab

dashboardsConfigMaps:
  lab: grafana-lab-dashboards
